source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-sass-converter", "~> 3.1"
gem "jekyll-email-protect"
gem "jekyll-feed"
gem "jekyll-link-attributes"
gem "jekyll-scholar"
gem "jekyll-sitemap"
gem "jekyll-toc"
gem "jemoji"
gem "webrick"
gem "base64"
gem "bigdecimal"
gem "csv"
